name: Build and deploy docs

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'

jobs:
  build-deploy-docs:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch the history for all tags and branches
          # so that the correct version string can be constructed
          # by setuptools_scm.
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements/minimal.txt
          pip install -r requirements/docs.txt

      - name: Build package
        run: |
          # Generate the version string which appears in the docs.
          python setup.py build

      - name: Build Docs
        run: |
          cd docs
          make dist

      - name: Checkout docs site
        if: (!github.event.pull_request)
        uses: actions/checkout@v2
        with:
          repository: popsim-consortium/demes-docs
          token: ${{ secrets.POPSIMBOT_DEMES_DOCS_TOKEN }}
          path: demes-docs

      - name: Copy our docs to the tag specific location
        if: (!github.event.pull_request)
        run: |
          cd demes-docs
          export DEST=`echo ${GITHUB_REF} | sed -e "s/refs\/heads\///g" |  sed -e "s/refs\/tags\///g"`
          rm -rf $DEST
          cp -r ../docs/_build/html $DEST

      - name: Commit and push the docs
        if: (!github.event.pull_request)
        run: |
          cd demes-docs
          git config user.name PopSim-bot
          git config user.email graham.gower+popsim-bot@gmail.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Automated doc build for ${GITHUB_REF}"
          git push
